
services:
  redis:
    image: redis:latest
    container_name: redis-app
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
