services:
  postgres:
    container_name: wallet_management
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres  # Default user (change if necessary)
      POSTGRES_PASSWORD: 123456 # Default password (change if necessary)
      POSTGRES_DB: wallet_db  # Database name
      PGDATA: /var/lib/postgresql/data  # Path to store data
    volumes:
      - wallet-service-db-data:/var/lib/postgresql/data1  # Mount volume for data persistence
    ports:
      - "5434:5432"  # Make sure this is correct based on your intention

volumes:
  wallet-service-db-data:
