version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: user_management
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    restart: always
